# Generated by Django 3.1.7 on 2021-05-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('phone_no', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
