# Generated by Django 3.1.7 on 2021-05-30 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=2000, null=True)),
                ('task_pic', models.URLField()),
                ('task_time_stamp', models.DateTimeField(auto_now_add=True)),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task1.signup1')),
            ],
        ),
    ]
